name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini 
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency.csv
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NOMBRE=nombre1
      - CLI_APELLIDO=apellido1
      - CLI_DOCUMENTO=1001
      - CLI_NACIMIENTO=1999-03-01
      - CLI_NUMERO=7111
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
